### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/tmp/plantuml-preview/test.svg'

### ISSUE THREAD

**Issue by ghost** [peele/plantuml-preview#9] opened 2016-01-10 12:43 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.3
**System**: Ubuntu 15.10
**Thrown From**: [plantuml-preview](https://github.com/peele/plantuml-preview) package, v0.11.0
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/tmp/plantuml-preview/test.svg'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/tmp/plantuml-preview/test.svg'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at /home/arjen/.atom/packages/plantuml-preview/lib/plantuml-preview-view.coffee:449:27
    at exit (/home/arjen/.atom/packages/plantuml-preview/lib/plantuml-preview-view.coffee:478:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
     -0:01.4.0 plantuml-preview:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
plantuml-preview, v0.11.0

# Dev
No dev packages
```

**Comment by peele** [comment] 2016-01-10 14:31
Going to need a bit more information. Are the paths to java and plantuml jar configured?

**Comment by peele** [comment] 2016-01-10 14:44
Believe this is a duplicate of #8.

**Closed as completed by peele** 2016-01-10 14:44 UTC

**Comment by ghost** [comment] 2016-01-10 15:57
I didn't configure any paths. Just installed plantuml out of the Ubuntu repository and was hopeful it would just work out of the box. Perhaps that's my mistake :smile:

**Comment by peele** [comment] 2016-01-10 16:52
Early on, and maybe still, Atom had some issues with picking up the system path on OS X. I made the decision to go with configuration values. The [README](https://github.com/peele/plantuml-preview/blob/master/README.md) should probably be updated to list the required configuration. 

With 0.11.1 the error messages should be informative and help resolve configuration issues.
